<#
.SYNOPSIS
  Creates the DoseMate MySQL databases and a dedicated least-privilege user.

.DESCRIPTION
  - Prompts for the MySQL root password (never echoed, never written to disk).
  - Generates a random password for the `dosemate` application user.
  - Creates `dosemate_dev` and `dosemate_test` schemas (utf8mb4).
  - Writes backend/dose-mate-api/.env (git-ignored) with DB_URL, DB_USERNAME,
    DB_PASSWORD, JWT_SECRET and JWT_EXPIRATION for local development.

.NOTES
  Run from the repository root:  powershell -ExecutionPolicy Bypass -File scripts\setup-database.ps1
#>
param(
    [string]$MySqlBin = 'C:\Program Files\MySQL\MySQL Server 8.0\bin',
    [string]$DbHost = '127.0.0.1',
    [int]$Port = 3306,
    [string]$AppUser = 'dosemate'
)

$ErrorActionPreference = 'Stop'
$mysql = Join-Path $MySqlBin 'mysql.exe'
if (-not (Test-Path $mysql)) { throw "mysql.exe not found at $mysql. Pass -MySqlBin <path>." }

$repoRoot = Split-Path -Parent $PSScriptRoot
$envFile  = Join-Path $repoRoot 'backend\dose-mate-api\.env'

function New-RandomSecret([int]$bytes) {
    $buf = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return [Convert]::ToBase64String($buf)
}

$secureRoot = Read-Host -AsSecureString "MySQL root password"
$rootPlain  = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
                [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureRoot))

# Alphanumeric app password avoids quoting issues in SQL / properties files.
$appPassword = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object { [char]$_ })
$jwtSecret   = New-RandomSecret 64

$sql = @"
CREATE DATABASE IF NOT EXISTS dosemate_dev  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS dosemate_test CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '$AppUser'@'localhost' IDENTIFIED BY '$appPassword';
CREATE USER IF NOT EXISTS '$AppUser'@'127.0.0.1' IDENTIFIED BY '$appPassword';
ALTER USER '$AppUser'@'localhost' IDENTIFIED BY '$appPassword';
ALTER USER '$AppUser'@'127.0.0.1' IDENTIFIED BY '$appPassword';
GRANT ALL PRIVILEGES ON dosemate_dev.*  TO '$AppUser'@'localhost', '$AppUser'@'127.0.0.1';
GRANT ALL PRIVILEGES ON dosemate_test.* TO '$AppUser'@'localhost', '$AppUser'@'127.0.0.1';
FLUSH PRIVILEGES;
"@

# Pass the root password via env var so it never appears on the command line / process list.
$env:MYSQL_PWD = $rootPlain
try {
    $sql | & $mysql --host=$DbHost --port=$Port --user=root --batch
    if ($LASTEXITCODE -ne 0) { throw "mysql exited with code $LASTEXITCODE" }
} finally {
    Remove-Item Env:\MYSQL_PWD -ErrorAction SilentlyContinue
    $rootPlain = $null
}

New-Item -ItemType Directory -Force (Split-Path $envFile) | Out-Null
@"
# Local development secrets - generated by scripts/setup-database.ps1
# THIS FILE IS GIT-IGNORED. Never commit it.
DB_URL=jdbc:mysql://${DbHost}:${Port}/dosemate_dev?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
DB_USERNAME=$AppUser
DB_PASSWORD=$appPassword
TEST_DB_URL=jdbc:mysql://${DbHost}:${Port}/dosemate_test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
JWT_SECRET=$jwtSecret
JWT_EXPIRATION=PT24H
"@ | Set-Content -Path $envFile -Encoding ASCII

Write-Host ""
Write-Host "OK: databases dosemate_dev / dosemate_test and user '$AppUser' are ready." -ForegroundColor Green
Write-Host "OK: local secrets written to $envFile (git-ignored)." -ForegroundColor Green
